// The Emscripten glue file (src/wasm-build/mqsim.mjs) is generated by
// engine/build-wasm.sh and gitignored, so there's no way to put a proper
// .d.ts alongside it. This is a deliberately loose ambient declaration -
// see src/hooks/useMqsimEngine.ts for the actual typed wrapper around what
// this module's default export resolves to.
declare module '*.mjs' {
  const createModule: (options?: Record<string, unknown>) => Promise<MqsimModule>;
  export default createModule;
}

// Shape of the object createMQSimModule() resolves to - the embind
// bindings exported from engine/mqsim/src/wasm/bindings.cpp. LPA/PPA come
// back as BigInt (64-bit types via embind), not number.
// address_to_val() in bindings.cpp only ever sets these five fields -
// `page` is added separately, only at the call sites that address one
// specific page rather than a whole block (see MqsimPageAddress below).
interface MqsimBlockAddress {
  channel: number;
  chip: number;
  die: number;
  plane: number;
  block: number;
}

interface MqsimPageAddress extends MqsimBlockAddress {
  page: number;
}

interface MqsimMappingRow {
  lpa: bigint;
  ppa: bigint | null;
  mapped: boolean;
  address: MqsimPageAddress | null;
}

type MqsimPageState = 'valid' | 'invalid' | 'free';
type MqsimBlockStatus = 'idle' | 'user' | 'gc_wl';

interface MqsimBlockSnapshot extends MqsimBlockAddress {
  eraseCount: number;
  // Always 'idle' - Block_Service_Status is only ever initialized in the
  // engine, never updated. Use hasOngoingGcWl below for real GC/WL state.
  status: MqsimBlockStatus;
  // True for the whole span between GC/WL picking this block as its victim
  // and its erase completing - the engine's own real race-condition flag
  // (Has_ongoing_gc_wl), unlike `status` above.
  hasOngoingGcWl: boolean;
  // True if this block is currently the host write frontier (Data_wf) for
  // some stream - where new user writes are actively landing, as opposed
  // to GC's migration destination or the mapping-table write frontier.
  isWriteFrontier: boolean;
  // True if this block is currently the GC/WL migration write frontier
  // (GC_wf) for some stream - where migrated pages are actively landing,
  // as opposed to hasOngoingGcWl above (the *victim* block being reclaimed).
  isGcWriteFrontier: boolean;
  // Which IO flow's data this block holds (0-based, flow order in the
  // workload XML), or null for a block erased back into the free pool.
  streamId: number | null;
  pages: MqsimPageState[]; // length == pages_no_per_block, indexed by page id
}

interface MqsimStats {
  issuedProgramCmd: number;
  gcExecutions: number;
  wlExecutions: number;
  // Host writes parked because their plane has no free pages left - still
  // nonzero once the run has ended means the device filled up and the
  // remaining writes could never be serviced.
  writesWaitingForSpace: number;
  // Times the engine gave up retrying GC on a stalled plane - nonzero means
  // a stall that is an engine problem, not just a full device.
  gcRetryLimitHits: number;
  // Free-block pool size of each plane (one per chip in this project), and
  // the pool size below which GC starts on a plane.
  freeBlocksPerPlane: number[];
  // Host requests completed so far (all flows) - one sector each here, so
  // compare with flash page writes to see what the DRAM write cache absorbed.
  hostRequestsServiced: number;
  gcThresholdBlocks: number;
}

interface MqsimState {
  mapping: MqsimMappingRow[];
  blocks: MqsimBlockSnapshot[];
  stats: MqsimStats;
}

interface MqsimEvent {
  type: string;
  streamId?: number;
  // mapping_updated: the LPA just translated. gc_page_migrated/
  // wl_page_migrated: the LPA this migration is moving - needed to keep a
  // "where does this LPA currently live" tracking map in sync with GC/WL
  // moves, not just host writes (a migration never fires mapping_updated).
  lpa?: bigint;
  ppa?: bigint;
  isWrite?: boolean;
  // mapping_updated only: the single page just translated.
  address?: MqsimPageAddress;
  // gc_*/wl_*/dynamic_wl_* only: the block the event is about. Only the two
  // *_page_migrated event types carry `page` (the specific page moved);
  // the others are block-wide (gc_started/gc_block_erased/wl_started/
  // wl_block_erased/dynamic_wl_block_allocated/dynamic_wl_block_freed).
  block?: MqsimBlockAddress | MqsimPageAddress;
  // gc_page_migrated/wl_page_migrated only: the destination page this
  // migration is writing to (`block` above is the source being vacated).
  newBlock?: MqsimPageAddress;
  eraseCount?: number;
  forMappingData?: boolean;
  dynamicWlConsidered?: boolean;
  // wl_started only: the condition that just triggered static WL. `block`
  // above is always the min-erase (coldest, chosen) block; maxEraseBlockId
  // is whichever block is currently hottest, for contrast. See
  // WL_Started_Event's doc comment in Simulation_Events.h for why these are
  // re-derived at notify time rather than captured once at the original
  // decision.
  minEraseCount?: number;
  maxEraseCount?: number;
  maxEraseBlockId?: number;
  threshold?: number;
  // gc_started only: why this victim - its page counts when GC started
  // (validPages are what must be moved) and the plane's free-block pool vs
  // the pool size below which GC starts.
  validPages?: number;
  invalidPages?: number;
  pagesPerBlock?: number;
  freeBlocks?: number;
  gcThresholdBlocks?: number;
}

interface MqsimModule {
  init(ssdConfigXml: string, workloadXml: string): void;
  configure(ssdConfigXml: string, workloadXml: string): void;
  step(): boolean;
  run(n: number): boolean;
  stepIo(): boolean;
  stepEvent(): boolean;
  // stepEvent() n times - see bindings.cpp's run_events().
  runEvents(n: number): boolean;
  getState(): MqsimState;
  setEventCallback(callback: ((event: MqsimEvent) => void) | null): void;
}
